title: things & stuff
email: aditya.tejpaul@research.iiit.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  by Aditya Tejpaul
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.adityatejpaul.com" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
github_username:  hoarfrost32

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .cache
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"

letterboxd:
  username: HoarfrostUmber
